name: weatherfit
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.1
  google_sign_in: ^6.1.0
  table_calendar: ^3.0.8
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  image_picker: ^0.8.7+4

  http: ^0.13.3
  geolocator: ^7.6.2
  permission_handler: ^8.3.0
  geocoding: ^2.0.1
  firebase_database: ^10.1.2
  introduction_screen: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Pretendart
      fonts:
        - asset: asset/fonts/Pretendard-Black.otf
          weight: 900
        - asset: asset/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: asset/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: asset/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: asset/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: asset/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: asset/fonts/Pretendard-Light.otf
          weight: 300
        - asset: asset/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: asset/fonts/Pretendard-Thin.otf
          weight: 100
  uses-material-design: true
  assets:
    - .env
    - asset/images/
    - asset/ic_google.png
    - asset/
